vich_uploader:
    db_driver: orm

    mappings:
        regions:
            uri_prefix: /images/regions
            upload_destination: '%kernel.project_dir%/public/images/regions'
        rooms:
            uri_prefix: /images/rooms
            upload_destination: '%kernel.project_dir%/public/images/regions'
